from python:3.11
run apt-get update && apt-get install -y --no-install-recommends \
    ffmpeg \
    libavcodec-dev \
    libavformat-dev \
    libavutil-dev \
    libswresample-dev \
    && rm -rf /var/lib/apt/lists/*

workdir /app

copy requirements.txt .

run pip install --default-timeout=100 --no-cache-dir \
    --index-url https://repo.huaweicloud.com/repository/pypi/simple \
    --trusted-host repo.huaweicloud.com \
    -r requirements.txt

copy . .
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
