from python:3.11

run apt-get update && apt-get install -y --no-install-recommends \ 
    gcc \
    python3-dev \
    libffi-dev \
    && rm -rf /var/lib/apt/lists/*

copy requirements.txt .
run pip install --no-cache-dir -r requirements.txt

copy . .
cmd ['uvicorn', 'main:app', '--host', '0.0.0.0', '--port', '8000', '--reload']